# Enterprise RAG System Configuration
# Customize these settings for your deployment

# System Paths
documents_dir: "./documents"
vector_db_dir: "./chroma_db"
cache_dir: "./.cache"

# Service Endpoints
# FIXED: Use Docker service name instead of localhost
ollama_host: "http://ollama:11434"
api_host: "0.0.0.0"
api_port: 7860

# Embedding Configuration
embedding:
  model_name: "nomic-embed-text"
  dimension: 768
  batch_size: 32
  cache_embeddings: true

# LLM Configuration
llm:
  model_name: "llama3.1:8b"
  temperature: 0.0
  top_p: 0.9
  top_k: 40
  num_ctx: 8192
  repeat_penalty: 1.1
  timeout: 120

# Chunking Strategy
chunking:
  # Options: "recursive", "semantic", "sentence", "hybrid"
  strategy: "hybrid"
  chunk_size: 800
  chunk_overlap: 200
  min_chunk_size: 100
  semantic_similarity_threshold: 0.7

# Advanced Retrieval
retrieval:
  # Multi-stage retrieval parameters
  initial_k: 50  # Initial candidates to retrieve
  rerank_k: 20   # Candidates after first reranking
  final_k: 5     # Final results to return
  
  # Hybrid search weights (must sum to 1.0)
  dense_weight: 0.5
  sparse_weight: 0.5
  
  # Fusion method: "rrf", "weighted", "score_normalization"
  fusion_method: "rrf"
  rrf_k: 60
  
  # Query enhancement
  use_query_expansion: true
  use_query_decomposition: true
  use_hypothetical_document: true
  
  # Reranking
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-12-v2"
  use_colbert_rerank: false
  
  # Filtering
  use_metadata_filtering: true
  relevance_threshold: 0.3

# Caching
cache:
  enable_embedding_cache: true
  enable_query_cache: true
  enable_result_cache: true
  
  cache_ttl: 3600  # seconds
  max_cache_size: 10000
  
  # Redis (optional - for distributed deployment)
  use_redis: false
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0

# Monitoring
monitoring:
  enable_logging: true
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/rag_system.log"
  
  enable_metrics: true
  metrics_port: 9090
  
  enable_tracing: false
  trace_sample_rate: 0.1

# Performance
performance:
  max_workers: 4
  enable_async: true
  connection_pool_size: 10
  
  # Batching
  enable_batching: true
  batch_timeout_ms: 100
  max_batch_size: 32

# Feature Flags
enable_evaluation: true
enable_feedback_loop: true
enable_auto_optimization: false