title: Apollo Documentation
description: Enterprise Document Intelligence Platform with GPU-Accelerated RAG
theme: jekyll-theme-cayman
baseurl: ""
url: "https://apollo.onyxlab.ai"

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Architecture
    url: /architecture
  - title: API Reference
    url: /api-reference
  - title: Configuration
    url: /configuration
  - title: Performance
    url: /performance

# Social
github_username: yourusername
repository: yourusername/apollo

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
