name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f _config/requirements.txt ]; then pip install -r _config/requirements.txt; fi
    
    - name: Check code formatting with Black
      run: black --check _src/
      continue-on-error: true
    
    - name: Lint with flake8
      run: |
        flake8 _src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 _src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -f _config/Dockerfile -t tactical-rag-system:${{ github.sha }} .
        
    - name: Test image was created
      run: |
        docker images | grep tactical-rag-system